name: A2 - Virtual Network Deployment

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - 'infrastructure/azure-resource-manager/virtual-network-deploy-arm-template.json'
  #     - '.github/workflows/azure-virtual-networks-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name todo-app \
            --location westeurope \
            --tags project=todo-app

      - name: Deploy Virtual Network
        id: todo-vnet-deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: 'todo-app'
          template: infrastructure/azure-resource-manager/virtual-network-deploy-arm-template.json
          parameters: >
            location=westeurope
            privateDnsZoneName=${{ secrets.POSTGRES_PRIVATE_DNS_NAME }}

      - name: Save DNS Zone ID
        run: |
          echo "PRIVATE_DNS_ZONE_ID=${{ steps.todo-vnet-deploy.outputs.privateDnsZoneId }}" >> $GITHUB_ENV
