name: 3 - Azure Container Registry Deploy

on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#     paths:
#       - 'infrastructure/container-registry-deploy-arm-template.json'
#       - '.github/workflows/deploy-acr.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container Registry
        id: deploy-acr
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: 'todo-app'
          template: infrastructure/container-registry-deploy-arm-template.json
          parameters: >
            acrName=todoappreg
            location=westeurope

      - name: Save ACR Login Server
        run: |
          echo "ACR_LOGIN_SERVER=${{ steps.deploy-acr.outputs.acrLoginServer }}" >> $GITHUB_ENV
