name: PostgreSQL Flexible Server Deploy

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - 'infrastructure/azure-resource-manager/azure-database-postgresql-deploy-arm-template.json'
  #     - '.github/workflows/deploy_postgres.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy PostgreSQL Server
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: 'todo-app'
          template: infrastructure/azure-resource-manager/azure-database-postgresql-deploy-arm-template.json
          parameters: >
            administratorLoginPassword=${{ secrets.POSTGRES_ADMIN_PASSWORD }}
            privateDnsZoneId=${{ secrets.POSTGRES_PRIVATE_DNS_ID }}
