name: B1 - Deploy PostgreSQL VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate SSH Key
        id: ssh-key
        run: |
          ssh-keygen -t rsa -b 4096 -f key -N ""
          # Format public key for JSON compatibility
          echo "PUBLIC_KEY='\"$(cat key.pub)\"'" >> $GITHUB_ENV
          echo "PRIVATE_KEY_BASE64=$(base64 -w0 key)" >> $GITHUB_ENV

      - name: Create parameters file
        run: |
          cat <<EOF > parameters.json
          {
            "vmName": { "value": "todo-postgres-vm" },
            "location": { "value": "westeurope" },
            "adminUsername": { "value": "azureuser" },
            "sshPublicKey": { "value": ${{ env.PUBLIC_KEY }} }
          }
          EOF

      - name: Deploy Postgres VM
        id: vm-deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: 'todo-app'
          template: infrastructure/azure-resource-manager/virtual-machines/deploy-postgres-vm.json
          parameters: parameters.json

      - name: Save connection info
        run: |
          echo "PUBLIC_IP=${{ steps.vm-deploy.outputs.publicIP }}" >> $GITHUB_ENV
          echo "SSH_COMMAND=ssh -i key.pem azureuser@${{ steps.vm-deploy.outputs.publicIP }}" >> $GITHUB_ENV

      - name: Connect to VM
        run: |
          echo "${{ env.PRIVATE_KEY_BASE64 }}" | base64 -d > key.pem
          chmod 400 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no azureuser@${{ env.PUBLIC_IP }} 'echo "Success!"'
