name: Build and Push Docker Image FastAPI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via Azure CLI
        run: az acr login --name todoappreg

      - name: Build and Push Docker Image FastAPI (backend)
        run: |
          docker build -t todoappreg.azurecr.io/fastapi-backend:latest ./backend
          docker push todoappreg.azurecr.io/fastapi-backend:latest
