name: B2 - React Build and Push Docker Image

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via Azure CLI
        run: az acr login --name todoappreg

      - name: React Build and Push Docker Image (frontend)
        run: |
          echo "Tagging image with: $IMAGE_TAG"
          docker build -t todoappreg.azurecr.io/react-frontend:$IMAGE_TAG ./frontend/todo
          docker push todoappreg.azurecr.io/react-frontend:$IMAGE_TAG

      - name: Call Deploy Workflow
        uses: kobiam/todo-app-infrastructure/.github/workflows/C2-Deploy-React-App-to-Azure-App-Service.yml@main
        with:
          imageTag: ${{ env.IMAGE_TAG }}
