name: C2 - Deploy React App to Azure App Service

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.imageTag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container Apps via ARM
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: todo-app
          template: infrastructure/azure-resource-manager/container-apps/deploy-container-apps-react.json
          parameters: >
            containerAppName=react-frontend
            acrServer=todoappreg.azurecr.io
            acrImage=react-frontend:${{ env.IMAGE_TAG }}
            acrUsername=${{ secrets.ACR_USERNAME }}
            acrPassword=${{ secrets.ACR_PASSWORD }}
          deploymentName: deploy-react-${{ github.run_id }}
