name: C3 - Deploy PostgreSQL DB to Azure App Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container Apps via ARM
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: todo-app
          template: infrastructure/azure-resource-manager/container-apps/deploy-container-apps-postgres.json
          parameters: >
            containerAppName=postgres-db
            acrServer=todoappreg.azurecr.io
            acrImage=postgres-db:latest
            acrUsername=${{ secrets.ACR_USERNAME }}
            acrPassword=${{ secrets.ACR_PASSWORD }}
          deploymentName: deploy-react-${{ github.run_id }}
