name: Deploy FastAPI Backend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR credentials
        id: acr-creds
        run: |
          USERNAME=$(az acr credential show --name todoappreg --query username -o tsv)
          PASSWORD=$(az acr credential show --name todoappreg --query passwords[0].value -o tsv)
          echo "acr_username=$USERNAME" >> $GITHUB_OUTPUT
          echo "acr_password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Deploy ARM Template
        run: |
          az deployment group create \
            --resource-group todo-app \
            --template-file infrastructure/azure-resource-manager/azure-deploy.json \
            --parameters webAppName=fastapi-backend-app \
                         serverFarmName=fastapi-backend-plan \
                         acrLoginServer=todoappreg.azurecr.io \
                         dockerImageName=todoappreg.azurecr.io/fastapi-backend:latest \
                         acrUsername=${{ steps.acr-creds.outputs.acr_username }} \
                         acrPassword=${{ steps.acr-creds.outputs.acr_password }}
