name: Build and Push Docker Image React

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via Azure CLI
        run: az acr login --name todoappreg

      - name: Build and Push Docker Image React (frontend)
        run: |
          docker build -t todoappreg.azurecr.io/react-frontend:latest ./frontend/todo
          docker push todoappreg.azurecr.io/react-frontend:latest
