name: Destroy Azure Infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        # run: terraform init -reconfigure
        run: terraform init -backend-config="storage_account_name=tfstateaccounttodoapp" -backend-config="container_name=tfstate" -backend-config="key=fastapi-app.tfstate" -backend-config="resource_group_name=todo-app"
        working-directory: infrastructure/aks-terraform

      - name: Terraform Force Unlock
        run: terraform force-unlock
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        working-directory: infrastructure/aks-terraform
        
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: infrastructure/aks-terraform
